Program/RabbitRegister/Pages/Main/Breeder/CreateBreeder.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Model;
using RabbitRegister.Services.BreederService;
using RabbitRegister.Pages.Main.Breeder;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNet.Identity;

namespace RabbitRegister.Pages.Main.Breeder
{
    public class CreateBreederModel : PageModel
    {
        private IBreederService _breederService;
        private PasswordHasher<string> _passwordHasher;


        public CreateBreederModel(IBreederService breederService)
        {
            _breederService = breederService;

            _passwordHasher = new PasswordHasher<string>();
        }

        [BindProperty]
        public Model.Breeder Breeder { get; set; } = new Model.Breeder();

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Model.Breeder breeder)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            breeder.Password = _passwordHasher.HashPassword(null, breeder.Password);
            await _breederService.AddUserAsync(breeder);
            return RedirectToPage("GetAllBreeders");
        }
    }
}

Program/RabbitRegister/Pages/Main/Breeder/DeleteBreeder.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Services.BreederService;
using RabbitRegister.Services.ProductService;

namespace RabbitRegister.Pages.Main.Breeder
{
    public class DeleteBreederModel : PageModel
    {
        private IBreederService _breederService;

        public DeleteBreederModel(IBreederService breederService)
        {
            _breederService = breederService;
        }

        [BindProperty]
        public Model.Breeder Breeder { get; set; }

        public IActionResult OnGet(int id)
        {
            Breeder = _breederService.GetBreeder(id);

            return Page();
        }

        public IActionResult OnPost(int id)
        {
            _breederService.DeleteBreederAsync(id);
            return RedirectToPage("GetAllBreeders");
        }
    }
}

Program/RabbitRegister/Pages/Main/Breeder/EditBreeder.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Model;
using RabbitRegister.Services.BreederService;
using RabbitRegister.Pages.Main.Breeder;
using RabbitRegister.Services.ProductService;
using Microsoft.AspNetCore.Identity;

namespace RabbitRegister.Pages.Main.Breeder
{
    public class EditBreederModel : PageModel
    {
        private IBreederService _breederService;
        private PasswordHasher<string> _passwordHasher;


        public EditBreederModel(IBreederService breederService)
        {
            _breederService = breederService;
            _passwordHasher = new PasswordHasher<string>();

        }

        public Model.Breeder Breeder { get; set; }


        public IActionResult OnGet(int Id)
        {
            Breeder = _breederService.GetBreeder(Id);
            return Page();
        }

        public async Task<IActionResult> OnPost(Model.Breeder breeder)
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }
            breeder.Password = _passwordHasher.HashPassword(null, breeder.Password);
            await _breederService.UpdateBreederAsync(breeder);
            if (User.IsInRole("Admin"))
            {
                return RedirectToPage("GetAllBreeders");
            }
            else
            {
                return RedirectToPage("/Index");
            }
            //return RedirectToPage("GetAllBreeders");
        }
    }
}

Program/RabbitRegister/Pages/Main/Breeder/GetAllBreeders.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Services.BreederService;
using RabbitRegister.Services.ProductService;
using Microsoft.AspNetCore.Authorization;


namespace RabbitRegister.Pages.Main.Breeder
{
    [Authorize(Roles = "Admin")]
    public class GetAllBreedersModel : PageModel
    {
        private IBreederService _breederService;

        public GetAllBreedersModel(IBreederService breederService)
        {
            _breederService = breederService;
        }

        public List<Model.Breeder>? Breeders { get; set; }


        public void OnGet()
        {
            Breeders = _breederService.GetBreeders();
        }
    }
}

Program/RabbitRegister/Pages/Main/LogIn/LogInPage.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using RabbitRegister.Services.BreederService;

namespace RabbitRegister.Pages.Main.LogIn
{
    public class LogInPageModel : PageModel
    {

        private IBreederService _breederService { get; set; }

        [BindProperty]
        public int BreederRegNo { get; set; }

        [BindProperty, DataType(DataType.Password)]
        public string Password { get; set; }
        public string Message { get; set; }

        public LogInPageModel(IBreederService breederService)
        {
            _breederService = breederService;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            List<Model.Breeder> breeders = _breederService.Breeders;
            foreach (Model.Breeder breeder in breeders)
            {
                if (BreederRegNo == breeder.BreederRegNo)
                {
                    var passwordHasher = new PasswordHasher<string>();

                    if (passwordHasher.VerifyHashedPassword(null, breeder.Password, Password) == PasswordVerificationResult.Success)
                    {
                        string UserName = BreederRegNo.ToString();
                        var claims = new List<Claim> { new Claim(ClaimTypes.Name, UserName), new Claim(ClaimTypes.Role, "Breeder") };

                        if (breeder.isAdmin)
                        {
                            claims.Add(new Claim(ClaimTypes.Role, "Admin"));
                        }

                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        var authProperties = new AuthenticationProperties
                        {
                            IsPersistent = true, // Remember user authentication across requests
                            ExpiresUtc = DateTimeOffset.UtcNow.AddDays(1) // Set expiration time for the authentication cookie
                        };

                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);
                        return RedirectToPage("/Index");
                    }
                }
            }

            Message = "Forkert Avler Id eller Adgangskode";
            return Page();
        }




    }

}

Program/RabbitRegister/Pages/Main/LogIn/LogOutPage.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RabbitRegister.Pages.Main.LogIn
{
    public class LogOutPageModel : PageModel
    {
        public async Task<IActionResult> OnGet()
        {

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/index");
        }
    }
}

Program/RabbitRegister/Pages/Main/Product/CreateWool.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Model;
using RabbitRegister.Services.ProductService;

namespace RabbitRegister.Pages.Main.Product
{
    [Authorize(Policy = "BreederOnly")]
    public class CreateWoolModel : PageModel
    {
        private IProductService _productService { get; set; }
        public Wool Wool { get; set; } = new Wool();

        public CreateWoolModel(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Wool wool)
        {
			if (!ModelState.IsValid)
			{
				return Page();
			}
			await _productService.AddWoolAsync(wool);
                
            return RedirectToPage("GetAllWool", new { breederRegNo = User.Identity.Name });

		}
        
    }
}

Program/RabbitRegister/Pages/Main/Product/CreateYarn.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Model;
using RabbitRegister.Services.ProductService;

namespace RabbitRegister.Pages.Main.Product
{
    [Authorize(Policy = "BreederOnly")]
    public class CreateYarnModel : PageModel
    {
		private IProductService _yarnService;

		public CreateYarnModel(IProductService productService)
		{
			_yarnService = productService;
		}

		[BindProperty]
		public Yarn Yarn { get; set; } = new Yarn();

		public IActionResult OnGet()
		{
			return Page();
		}

		public async Task<IActionResult> OnPostAsync(Yarn yarn)
		{
			if(!ModelState.IsValid)
			{
				return Page();
			}
			await _yarnService.AddYarnAsync(yarn);
			return RedirectToPage("GetAllYarn", new { breederRegNo = User.Identity.Name });
		}
	}
}

Program/RabbitRegister/Pages/Main/Product/DeleteWool.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Model;
using RabbitRegister.Services.ProductService;

namespace RabbitRegister.Pages.Main.Product
{
    [Authorize(Policy = "BreederOnly")]
    public class DeleteWoolModel : PageModel
    {
        private IProductService _productService;

        public DeleteWoolModel(IProductService productService)
        {
            _productService = productService;
        }

        [BindProperty]
        public Wool Wool { get; set; }

        public IActionResult OnGet(int id)
        {
            Wool = _productService.GetWools(id);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int Id)
        {
            await _productService.DeleteWoolAsync(Id);
			return RedirectToPage("GetAllWool", new { breederRegNo = User.Identity.Name });
		}
	}
}

Program/RabbitRegister/Pages/Main/Product/DeleteYarn.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Model;
using RabbitRegister.Services.ProductService;

namespace RabbitRegister.Pages.Main.Product
{
    [Authorize(Policy = "BreederOnly")]
    public class DeleteYarnModel : PageModel
    {

		private IProductService _yarnService;

		public DeleteYarnModel(IProductService productService)
		{
			_yarnService = productService;
		}

		[BindProperty]
		public Model.Yarn Yarn { get; set; }


		public IActionResult OnGet(int Id)
		{
			Yarn = _yarnService.GetYarn(Id);
			

			return Page();
		}

		public IActionResult OnPost(int Id)
		{
			_yarnService.DeleteYarnAsync(Id);
			return RedirectToPage("GetAllYarn", new { breederRegNo = User.Identity.Name });
		}
	}
}

Program/RabbitRegister/Pages/Main/Product/EditWool.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Model;
using RabbitRegister.Services.ProductService;

namespace RabbitRegister.Pages.Main.Product
{
    [Authorize(Policy = "BreederOnly")]
    public class EditWoolModel : PageModel
    {
        private IProductService _productService;

        public EditWoolModel(IProductService productService)
        {
            _productService = productService;
        }

        [BindProperty]
        public Model.Wool Wool { get; set; }

        public IActionResult OnGet(int id)
        {
            Wool = _productService.GetWools(id);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Wool Wool)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            await _productService.UpdateWoolAsync(Wool);
			return RedirectToPage("GetAllWool", new { breederRegNo = User.Identity.Name });
		}
	}
}

Program/RabbitRegister/Pages/Main/Product/EditYarn.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Services.ProductService;

namespace RabbitRegister.Pages.Main.Product
{
    [Authorize(Policy = "BreederOnly")]
    public class EditYarnModel : PageModel
	{
		private IProductService _yarnService;

		public EditYarnModel(IProductService productService)
		{
			_yarnService = productService;
		}

		[BindProperty]
		public Model.Yarn Yarn { get; set; }

		public IActionResult OnGet(int Id)
		{
			Yarn = _yarnService.GetYarn(Id);
			return Page();
		}

		public IActionResult OnPost(int id)
		{
			_yarnService.UpdateYarnAsync(Yarn, id);
			return RedirectToPage("GetAllYarn", new { breederRegNo = User.Identity.Name });
		}
	}
}

Program/RabbitRegister/Pages/Main/Product/GetAllWool.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Model;
using RabbitRegister.Services.ProductService;
using System.Runtime.CompilerServices;

namespace RabbitRegister.Pages.Main.Product
{
    public class GetAllWoolModel : PageModel
    {
        private IProductService _productService { get; set; }
        public List<Model.Wool> Wools { get; set; }

        public GetAllWoolModel(IProductService productService)
        {
            _productService = productService;
        }

		public IActionResult OnGet(int breederRegNo)
		{
			Wools = _productService.GetMyWoolCreations(breederRegNo);

			return Page();
		}

		//public void OnGet()
		//{
		//    Wools = _productService.GetWools();
		//}

		public void OnPost()
        {

        }
    }
}

Program/RabbitRegister/Pages/Main/Product/GetAllYarn.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Model;
using RabbitRegister.Services.ProductService;

namespace RabbitRegister.Pages.Main.Product
{
    public class GetAllYarnModel : PageModel
    {
		private IProductService _yarnService;

		public GetAllYarnModel(IProductService productService)
		{
			_yarnService = productService;
		}

		//public List<Model.Yarn>? Yarns { get; set; }
		public List<Model.Yarn> Yarns { get; set; }

		public IActionResult OnGet(int breederRegNo)
		{
			Yarns = _yarnService.GetMyYarnCreations(breederRegNo);

			return Page();
		}

		//public void OnGet()
		//{
		//	Yarns = _yarnService.GetYarns();
		//}
	}
}

Program/RabbitRegister/Pages/Main/Rabbit/GetAllRabbits.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Pages.Main.LogIn;
using RabbitRegister.Model;
using RabbitRegister.Services.RabbitService;
using RabbitRegister.Services.BreederService;
using Microsoft.AspNetCore.Authorization;

namespace RabbitRegister.Pages.Main.Rabbit
{
    [Authorize(Policy = "BreederOnly")]
    public class GetAllRabbitsModel : PageModel
    {
        private IRabbitService _rabbitService;

        public GetAllRabbitsModel(IRabbitService rabbitService)
        {
            _rabbitService = rabbitService;
        }

        public List<Model.Rabbit>? Rabbits { get; private set; }

        [BindProperty]
        public string SearchString { get; set; }

        [BindProperty]
        public int MinRating { get; set; }


        public IActionResult OnGet(int breederRegNo, string action)
        {
            if (action == "OwnedDeadRabbits")
            {
                Rabbits = _rabbitService.GetOwnedDeadRabbits(breederRegNo);
            }          
            else if (action == "AllRabbitsWithConnectionsToMe")
            {
                Rabbits = _rabbitService.GetAllRabbitsWithConnectionsToMe(breederRegNo);
            }
            else if (action == "NotOwnedRabbitsWithMyBreederRegNo")
            {
                Rabbits = _rabbitService.GetNotOwnedRabbitsWithMyBreederRegNo(breederRegNo);
            }           
            else
            {
                Rabbits = _rabbitService.GetOwnedAliveRabbits(breederRegNo);
            }

            return Page();
        }


        public IActionResult OnPostNameSearch()
        {
            Rabbits = _rabbitService.NameSearch(SearchString).ToList();
            return Page();
        }

  
    }
}

Program/RabbitRegister/Pages/Main/Rabbit/RabbitProfile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitRegister.Model;
using RabbitRegister.Services.RabbitService;

namespace RabbitRegister.Pages.Main.Rabbit
{
    public class RabbitProfileModel : PageModel
    {
        private IRabbitService _rabbitService;

        public RabbitProfileModel(IRabbitService rabbitService)
        {
            _rabbitService = rabbitService;
        }

        [BindProperty]
        public Model.Rabbit Rabbit { get; set; }

        public IActionResult OnGet(int id, int breederRegNo)
        {
            Rabbit = _rabbitService.GetRabbit(id, breederRegNo);
            //if (Rabbit == null)
            //    return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return Page();
        }
    }
}

Program/RabbitRegister/Pages/Main/Trimming/CreateTrimming.cshtml
@page
@model RabbitRegister.Pages.Main.Trimming.CreateTrimmingModel
@{
}
<form method="post">
	<div class="form-group">
		<label asp-for="@Model.Trimming.RabbitRegNo" class="control-label"></label>
		<input asp-for="@Model.Trimming.RabbitRegNo" class="form-control" />
		<span asp-validation-for="@Model.Trimming.RabbitRegNo" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="@Model.Trimming.BreederRegNo" class="control-label"></label>
		<input asp-for="@Model.Trimming.BreederRegNo" class="form-control" />
		<span asp-validation-for="@Model.Trimming.BreederRegNo" class="text-danger"></span>
	</div>
		<div class="form-group">
		<label asp-for="@Model.Trimming.Name" class="control-label"></label>
		<input asp-for="@Model.Trimming.Name" class="form-control" />
		<span asp-validation-for="@Model.Trimming.Name" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="@Model.Trimming.Date" class="control-label"></label>
		<input asp-for="@Model.Trimming.Date" class="form-control" />
		<span asp-validation-for="@Model.Trimming.Date" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="@Model.Trimming.TimeUsed" class="control-label"></label>
		<input asp-for="@Model.Trimming.TimeUsed" class="form-control" />
		<span asp-validation-for="@Model.Trimming.TimeUsed" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="@Model.Trimming.HairLengthByDayNinety" class="control-label"></label>
		<input asp-for="@Model.Trimming.HairLengthByDayNinety" class="form-control" />
		<span asp-validation-for="@Model.Trimming.HairLengthByDayNinety" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="@Model.Trimming.WoolDensity" class="control-label"></label>
		<input asp-for="@Model.Trimming.WoolDensity" class="form-control" />
		<span asp-validation-for="@Model.Trimming.WoolDensity" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="@Model.Trimming.FirstSortmentWeight" class="control-label"></label>
		<input asp-for="@Model.Trimming.FirstSortmentWeight" class="form-control" />
		<span asp-validation-for="@Model.Trimming.FirstSortmentWeight" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="@Model.Trimming.SecondSortmentWeight" class="control-label"></label>
		<input asp-for="@Model.Trimming.SecondSortmentWeight" class="form-control" />
		<span asp-validation-for="@Model.Trimming.SecondSortmentWeight" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="@Model.Trimming.DisposableWoolWeight" class="control-label"></label>
		<input asp-for="@Model.Trimming.DisposableWoolWeight" class="form-control" />
		<span asp-validation-for="@Model.Trimming.DisposableWoolWeight" class="text-danger"></span>
	</div>


	<p>
		<div class="form-group">
			<input type="submit" value="Create" class="btn btn-primary" />
		</div>
	</p>
</form>

<form>
	<input type="button" value="Back" onclick="history.go(-1)">
</form>

Program/RabbitRegister/Pages/Main/Trimming/DeleteTrimming.cshtml
@page "{id:int}"
@model RabbitRegister.Pages.Main.Trimming.DeleteTrimmingModel
@{
}

<h1>Delete Trimming</h1>

<h3>Are you sure you want to delete the selected Trimming?</h3>
<div>
    <h4>Deleting...</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Trimming.TrimmingId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Trimming.TrimmingId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Trimming.RabbitRegNo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Trimming.RabbitRegNo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Trimming.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Trimming.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Trimming.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Trimming.Date)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="Trimming.TrimmingId" />
        <button type="submit" class="btn btn-danger">Yes</button>
        <a class="btn btn-primary" asp-route-Owner="@User.Identity.Name" asp-page="/Main/Trimming/GetAllTrimming">No</a>
    </form>
</div>

Program/RabbitRegister/Pages/Main/Trimming/GetAllTrimming.cshtml
@page
@model RabbitRegister.Pages.Main.Trimming.GetAllTrimmingModel
@{
    ViewData["Title"] = "Trimmings";
}

<body>
    <form method="post" class="form-inline">
        <div class="input-group mb-3">
            <input asp-for="SearchString" class="form-control mr-1" placeholder="Søg efter navn" />
            <input type="submit" asp-route-Owner="@User.Identity.Name" asp-page-handler="NameSearch" value="Search" class="btn btn-primary" />
        </div>
    </form>
@*    <form method="post" class="form-inline">
        <div class="input-group mb-3">
            <input asp-for="SearchId" class="form-control mr-1" placeholder="Søg efter Kanin ID" />
            <input type="submit" asp-page-handler="RabbitIdSearch" value="Search" class="btn btn-primary" />
        </div>
    </form>*@

    <h1 class="font-monospace text-center">Trimmings</h1>
    <div class="container-all">
        <h1></h1>
        <p class="from-group">
            <a class="btn btn-primary text-center" style="background-color:green;margin-left:auto;margin-right:auto;display:block;margin-top:1%" asp-route-Owner="@User.Identity.Name" asp-page="/Main/Trimming/CreateTrimming"> Create a new Trimming </a>
        </p>

        <table class="table table-bordered table-hover table-striped table-opacity" width="100%">
            <thead>
                <tr>
                    <th>
                        Klip ID
                        <div>
                            <a data-toggle="tooltip" title="Sort By Id" asp-route-Owner="@User.Identity.Name" asp-page-handler="SortById"><i class="fa fa-angle-up"></i></a>
                            <a data-toggle="tooltip" title="Sort By Id Descending" asp-route-Owner="@User.Identity.Name" asp-page-handler="SortByIdDescending"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </th>
                    <th>
                        Kanin ID
@*                        <div>
                            <a data-toggle="tooltip" title="Sort By Id" asp-page-handler="SortByRabbitId"><i class="fa fa-angle-up"></i></a>
                            <a data-toggle="tooltip" title="Sort By Id Descending" asp-page-handler="SortByRabbitIdDescending"><i class="fa fa-angle-down"></i></a>
                        </div>*@
                    </th>
                    <th> Avler ID  </th>
                    <th> Navn  </th>
                    <th>
                        Dato
                        <div>
                            <a data-toggle="tooltip" title="Sort By Date" asp-route-Owner="@User.Identity.Name" asp-page-handler="SortByDate"><i class="fa fa-angle-up"></i></a>
                            <a data-toggle="tooltip" title="Sort By Date Descending" asp-route-Owner="@User.Identity.Name" asp-page-handler="SortByDateDescending"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </th>
                    <th> Tid i min </th>
                    <th> Hår dag 90 </th>
                    <th> Uld tæthed </th>
                    <th> 1. Sortering </th>
                    <th> 2. Sortering </th>
                    <th> Kasseret Uld </th>
                    <th> Actions </th>
                </tr>
            </thead>
            <tbody>

                @if (Model.Trimmings != null)
                {
                    @foreach (var item in Model.Trimmings)
                    {
                        <tr>
                            <td> @item.TrimmingId </td>
                            <td> @item.RabbitRegNo </td>
                            <td> @item.BreederRegNo </td>
                            <td> @item.Name </td>
                            <td> @item.Date.ToString("dd-MM-yyyy") </td>
                            <td> @item.TimeUsed </td>
                            <td> @item.HairLengthByDayNinety </td>
                            <td> @item.WoolDensity </td>
                            <td> @item.FirstSortmentWeight </td>
                            <td> @item.SecondSortmentWeight </td>
                            <td> @item.DisposableWoolWeight </td>
                            <td>
                                <a class="btn btn-primary btn-sm" type="button" title="Edit" asp-route-Owner="@User.Identity.Name" asp-page="EditTrimming" asp-route-id="@item.TrimmingId"><i class="fa fa-edit"></i></a>
                                <a class="btn btn-danger btn-sm " type="button" title="Delete" asp-route-Owner="@User.Identity.Name" asp-page="DeleteTrimming" asp-route-id="@item.TrimmingId"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</body>